// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewjdnprimnbkbubdfrnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3amRucHJpbW5ia2J1YmRmcm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTc0NTksImV4cCI6MjA2NjE3MzQ1OX0.TdSutBDk-p8RvuOHUXha_JraCKfo1er03j82qHtalB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);